apiVersion: v1
kind: Service
metadata:
  name: icamps-admin-frontend-service
  namespace: icamps
  labels:
    environment: dev
    application: icamps
spec:
  type: NodePort
  selector:
    app: icamps-admin-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
